/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lightweight health check for load balancers and Kamal proxy. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Healthy */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health/deep': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Deep health check including DB, file store, GitHub App, and LLM. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description All checks healthy */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeepHealthResponse'];
          };
        };
        /** @description One or more subsystems degraded */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeepHealthResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/openapi.yaml': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** This OpenAPI contract (YAML). */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OpenAPI 3.0 YAML document */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/yaml': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** High-level site statistics. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Stats */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['StatsResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/skills': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search and list skills. */
    get: {
      parameters: {
        query?: {
          q?: string;
          cat?: string[];
          tag?: string[];
          size?: '<2k' | '2-5k' | '5k+';
          verified?: boolean;
          sort?: 'relevance' | 'installs' | 'updated' | 'tokens';
          page?: number;
          pageSize?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Paginated search results */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SkillSearchPage'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/skills/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Full skill detail. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Skill detail */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SkillDetail'];
          };
        };
        /** @description Skill not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/skills/{slug}/files': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** File tree for a skill. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description File tree */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FileTreeResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/skills/{slug}/files/{path}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** File content (or raw text preview). */
    get: {
      parameters: {
        query?: {
          raw?: boolean;
        };
        header?: never;
        path: {
          slug: string;
          /** @description Path segments are joined with `/`. */
          path: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description File content or raw text */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FileContentResponse'];
            'text/plain': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/skills/{slug}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Version history for a skill. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Versions */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['VersionsResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/skills/{slug}/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download a skill archive. */
    get: {
      parameters: {
        query?: {
          version?: string;
        };
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Skill archive */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/octet-stream': string;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/skills/{slug}/report': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Report a skill. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ReportRequest'];
        };
      };
      responses: {
        /** @description Report accepted */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReportResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List categories with counts. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Categories */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CategoryWithCount'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/trends': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Trends and aggregations. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Trends */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TrendsResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timeline': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Recent publish/version timeline. */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Timeline */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TimelinePage'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bundles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List bundles. */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Bundles */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PageOfBundleSummary'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bundles/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Bundle detail. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Bundle detail */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BundleDetail'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/authors/{handle}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Author profile. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          handle: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Author profile */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthorProfile'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/github/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Start GitHub OAuth flow. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect to GitHub */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/github/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GitHub OAuth callback. */
    get: {
      parameters: {
        query?: {
          code?: string;
          state?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect to site root on success */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description OAuth error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log out current session. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Logged out */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OkResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Soft-delete the current account. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/repos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List repos for the current user's GitHub App installations. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Repositories */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReposResponse'];
          };
        };
        /** @description GitHub App disabled */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/repos/{owner}/{repo}/scan': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Scan a repo for skills. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          owner: string;
          repo: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Scan results */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ScanResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/submissions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List my submissions grouped by state. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Submissions */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GroupedSubmissions'][];
          };
        };
      };
    };
    put?: never;
    /** Create draft submissions from selected skills. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateDraftsRequest'];
        };
      };
      responses: {
        /** @description Drafts created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CreateDraftsResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/submissions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a submission detail. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Submission detail */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SubmissionDetail'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete a draft submission. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/submissions/{id}/submit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit a draft for review. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Submitted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OkResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/submissions/{id}/withdraw': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Withdraw a submission back to draft. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Withdrawn */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OkResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/stars': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List starred skills. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Starred skill cards */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SkillCard'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/stars/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Star a skill. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Starred */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OkResponse'];
          };
        };
      };
    };
    /** Unstar a skill. */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Unstarred */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user settings. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': Record<string, never>;
          };
        };
      };
    };
    /** Update user settings. */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': Record<string, never>;
        };
      };
      responses: {
        /** @description Updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OkResponse'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/skills/{slug}/unpublish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Unpublish a skill. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Unpublished */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OkResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/skills/{slug}/resync': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enqueue a resync from the source repo. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Resync enqueued */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OkResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthResponse: {
      ok: boolean;
      version: string;
      db: string;
      fileStore: string;
      llm: string;
      auth: string;
    };
    DeepHealthResponse: {
      status: string;
      checks: {
        database: boolean;
        fileStore: boolean;
        githubApp: boolean;
        llm: boolean;
      };
    };
    StatsResponse: {
      indexed: number;
      contributors: number;
      lastUpdated: string | null;
    };
    CategoryRef: {
      slug: string;
      name: string;
    };
    AuthorRef: {
      handle: string;
      name?: string | null;
      avatarUrl?: string | null;
    };
    BundleRef: {
      id: string;
      kind: string;
      provenance: string;
    };
    SkillCard: {
      id: string;
      slug: string;
      name: string;
      description: string;
      license: string | null;
      tags: string[];
      category: components['schemas']['CategoryRef'] | null;
      version: string;
      versionSource: string;
      tokenUpfront: number;
      tokenOndemand: number;
      tokenBand: string;
      verified: boolean;
      status: string;
      featured: boolean;
      installs: number;
      author: components['schemas']['AuthorRef'];
      bundle: components['schemas']['BundleRef'];
      createdAt: string;
      updatedAt: string;
    };
    SkillDetail: components['schemas']['SkillCard'] & {
      readmeMd: string | null;
      fileCount: number;
      /** Format: int64 */
      totalSize: number;
    };
    FacetCount: {
      key: string;
      label?: string | null;
      count: number;
    };
    Facets: {
      categories: components['schemas']['FacetCount'][];
      tags: components['schemas']['FacetCount'][];
      sizes: components['schemas']['FacetCount'][];
    };
    SkillSearchPage: {
      items: components['schemas']['SkillCard'][];
      page: number;
      pageSize: number;
      total: number;
      totalPages: number;
      facets: components['schemas']['Facets'];
    };
    FileEntry: {
      path: string;
      name: string;
      dir: string;
      size: number;
      isBinary: boolean;
    };
    TreeNode: {
      name: string;
      path: string;
      /** @enum {string} */
      type: 'file' | 'dir';
      size?: number;
      isBinary?: boolean;
      children?: components['schemas']['TreeNode'][] | null;
    };
    FileTreeResponse: {
      slug: string;
      files: components['schemas']['FileEntry'][];
      tree: components['schemas']['TreeNode'][];
    };
    FileContentResponse: {
      slug: string;
      path: string;
      size: number;
      isBinary: boolean;
      content?: string | null;
      downloadOnly: boolean;
      downloadUrl?: string | null;
    };
    VersionEntry: {
      version: string;
      sourceRef: string;
      createdAt: string;
      current: boolean;
    };
    VersionsResponse: {
      slug: string;
      current: string;
      versions: components['schemas']['VersionEntry'][];
    };
    CategoryWithCount: {
      id: string;
      slug: string;
      name: string;
      count: number;
    };
    TrendsResponse: {
      categories: components['schemas']['FacetCount'][];
      tags: components['schemas']['FacetCount'][];
      tokenMix: components['schemas']['FacetCount'][];
      /** Format: double */
      securityPassRate: number | null;
      submissionFunnel: {
        [key: string]: number;
      };
    };
    TimelineEvent: {
      /** @enum {string} */
      type: 'publish' | 'version';
      at: string;
      slug: string;
      name: string;
      version?: string | null;
      authorHandle?: string | null;
    };
    TimelinePage: {
      items: components['schemas']['TimelineEvent'][];
      page: number;
      pageSize: number;
      total: number;
      totalPages: number;
    };
    PageOfBundleSummary: {
      items: components['schemas']['BundleSummary'][];
      page: number;
      pageSize: number;
      total: number;
      totalPages: number;
    };
    BundleSummary: {
      id: string;
      kind: string;
      provenance: string;
      owner: components['schemas']['AuthorRef'];
      sourceRef?: string | null;
      skillCount: number;
      syncedAt?: string | null;
      createdAt: string;
    };
    BundleDetail: {
      id: string;
      kind: string;
      provenance: string;
      owner: components['schemas']['AuthorRef'];
      sourceRef?: string | null;
      syncedAt?: string | null;
      createdAt: string;
      skills: components['schemas']['SkillCard'][];
    };
    AuthorProfile: {
      handle: string;
      name?: string | null;
      avatarUrl?: string | null;
      skillCount: number;
      totalInstalls: number;
      skills: components['schemas']['SkillCard'][];
    };
    ErrorBody: {
      code: string;
      message: string;
      details?: {
        [key: string]: string;
      } | null;
    };
    ErrorResponse: {
      error: components['schemas']['ErrorBody'];
    };
    OkResponse: {
      ok: boolean;
    };
    MeResponse: {
      id: string;
      handle: string;
      name: string | null;
      avatarUrl: string | null;
      role: string;
      status: string;
      createdAt: string;
    };
    RepoDto: {
      owner: string;
      name: string;
      fullName: string;
      defaultBranch?: string | null;
    };
    ReposResponse: {
      repos: components['schemas']['RepoDto'][];
    };
    DetectedFieldError: {
      field: string;
      reason: string;
    };
    DetectedSkillDto: {
      slug: string;
      sourceDir: string;
      name: string;
      description: string;
      license: string | null;
      tags: string[];
      version: string;
      versionSource: string;
      tokenUpfront: number;
      tokenOndemand: number;
      tokenBand: string;
      parseErrors: components['schemas']['DetectedFieldError'][];
      fileCount: number;
    };
    ScanResponse: {
      slug: string;
      commitSha: string;
      skills: components['schemas']['DetectedSkillDto'][];
    };
    SelectedSkill: {
      slug: string;
      sourceDir?: string | null;
      name: string;
      description: string;
      license: string;
      tags?: string[];
      version?: string | null;
    };
    CreateDraftsRequest: {
      repoOwner: string;
      repoName: string;
      ref: string;
      skills: components['schemas']['SelectedSkill'][];
    };
    CreateDraftsResponse: {
      submissionIds: string[];
      slugs?: string[];
    };
    SubmissionSummary: {
      id: string;
      slug: string;
      state: string;
      lintScore?: number | null;
      createdAt: string;
      updatedAt: string;
    };
    GroupedSubmissions: {
      state: string;
      items: components['schemas']['SubmissionSummary'][];
    };
    SubmissionDetail: {
      id: string;
      slug: string;
      state: string;
      lintScore?: number | null;
      note?: string | null;
      payload?: Record<string, never> | null;
      createdAt: string;
      updatedAt: string;
    };
    ReportRequest: {
      reason?: string | null;
    };
    ReportResponse: {
      id: string;
      accepted: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
