/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/admin/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Dashboard aggregate counts. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Counts */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminStatsResponse'];
          };
        };
        /** @description Not found (non-admin or anonymous) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/queue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List active review queue items. */
    get: {
      parameters: {
        query?: {
          filter?: 'all' | 'in_review' | 'changes_requested';
          q?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Queue items */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminQueueItem'][];
          };
        };
        /** @description Not found (non-admin or anonymous) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/queue/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Queue item detail. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Queue detail */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminQueueDetail'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/queue/{id}/decision': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve, request changes, reject, or skip a submission. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AdminDecisionRequest'];
        };
      };
      responses: {
        /** @description Decision recorded */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OkResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Conflict (e.g., duplicate skill) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/skills': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List skills for administration. */
    get: {
      parameters: {
        query?: {
          filter?: 'published' | 'unlisted' | 'flagged';
          q?: string;
          sort?: 'updated' | 'installs' | 'created' | 'name';
          page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Skill list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminSkillListItem'][];
          };
        };
        /** @description Not found (non-admin or anonymous) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/skills/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch a skill's admin-only fields. */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AdminSkillPatch'];
        };
      };
      responses: {
        /** @description Patched */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OkResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/admin/skills/bulk': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bulk feature/unlist/delete skills. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AdminBulkActionRequest'];
        };
      };
      responses: {
        /** @description Bulk results */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminBulkActionResponse'];
          };
        };
        /** @description Not found (non-admin or anonymous) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List users for administration. */
    get: {
      parameters: {
        query?: {
          filter?: 'active' | 'suspended';
          q?: string;
          page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminUserListItem'][];
          };
        };
        /** @description Not found (non-admin or anonymous) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export users as CSV. */
    get: {
      parameters: {
        query?: {
          filter?: 'active' | 'suspended';
          q?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description CSV download */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/csv': string;
          };
        };
        /** @description Not found (non-admin or anonymous) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch a user's role or status. */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AdminUserPatch'];
        };
      };
      responses: {
        /** @description Patched */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OkResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Conflict (self-guard or last admin) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/admin/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List categories. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Categories */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminCategoryDto'][];
          };
        };
        /** @description Not found (non-admin or anonymous) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /** Create a category. */
    post: {
      parameters: {
        query: {
          slug: string;
          name: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Created category */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminCategoryDto'];
          };
        };
        /** @description Not found (non-admin or anonymous) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Duplicate slug */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/categories/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Rename a category. */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AdminCategoryRenameRequest'];
        };
      };
      responses: {
        /** @description Renamed category */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminCategoryDto'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Duplicate slug */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/admin/categories/{slug}/merge': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Merge a category into another. */
    post: {
      parameters: {
        query: {
          to: string;
        };
        header?: never;
        path: {
          slug: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Merged */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OkResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Cannot merge into self */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get platform settings. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Platform settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminPlatformSettings'];
          };
        };
        /** @description Not found (non-admin or anonymous) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    /** Update platform settings. */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AdminPlatformSettings'];
        };
      };
      responses: {
        /** @description Updated settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminPlatformSettings'];
          };
        };
        /** @description Not found (non-admin or anonymous) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List audit log entries. */
    get: {
      parameters: {
        query?: {
          action?: string;
          target?: string;
          page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Audit log entries */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuditLogEntry'][];
          };
        };
        /** @description Not found (non-admin or anonymous) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AdminStatsResponse: {
      /** @description Total number of users. */
      users: number;
      /** @description Users with role contributor. */
      contributors: number;
      /** @description Users created in the last 30 days. */
      newUsers30d: number;
      /** @description Users with status suspended. */
      suspended: number;
      /** @description Total number of skills. */
      skills: number;
      /** @description Active submissions in in_review or changes_requested. */
      queue: number;
    };
    AdminQueueItem: {
      id: string;
      slug: string;
      state: string;
      submitterHandle: string;
      lintScore?: number | null;
      review?: components['schemas']['ReviewOutputPayload'];
      staged?: components['schemas']['StagedPayload'];
      createdAt: string;
      updatedAt: string;
    };
    AdminQueueDetail: {
      id: string;
      slug: string;
      state: string;
      submitterHandle: string;
      lintScore?: number | null;
      note?: string | null;
      payload?: components['schemas']['SubmissionPayload'];
      files: components['schemas']['AdminSkillFileSummary'][];
      provenance: string;
      sourceRef: string;
      reviewIsMetadataOnly: boolean;
      createdAt: string;
      updatedAt: string;
    };
    AdminSkillFileSummary: {
      path: string;
      size: number;
      isBinary: boolean;
    };
    AdminDecisionRequest: {
      /** @enum {string} */
      decision: 'approve' | 'request_changes' | 'reject' | 'skip';
      note?: string | null;
    };
    AdminSkillListItem: {
      id: string;
      slug: string;
      name: string;
      status: string;
      verified: boolean;
      featured: boolean;
      categoryId?: string | null;
      categorySlug?: string | null;
      installs: number;
      updatedAt: string;
    };
    AdminSkillPatch: {
      featured?: boolean | null;
      /** @enum {string|null} */
      status?: 'published' | 'unlisted' | 'flagged' | null;
      categoryId?: string | null;
    };
    AdminBulkActionRequest: {
      ids: string[];
      /** @enum {string} */
      action: 'feature' | 'unlist' | 'delete';
    };
    AdminBulkActionResponse: {
      results: {
        [key: string]: boolean;
      };
      failed: {
        [key: string]: string;
      };
    };
    AdminUserListItem: {
      id: string;
      handle: string;
      role: string;
      status: string;
      skillCount: number;
      createdAt: string;
    };
    AdminUserPatch: {
      /** @enum {string|null} */
      role?: 'member' | 'contributor' | 'admin' | null;
      /** @enum {string|null} */
      status?: 'active' | 'suspended' | null;
    };
    AdminCategoryDto: {
      id: string;
      slug: string;
      name: string;
    };
    AdminCategoryRenameRequest: {
      name?: string | null;
      slug?: string | null;
    };
    AdminPlatformSettings: {
      /**
       * @default manual
       * @enum {string}
       */
      reviewPolicy: 'manual' | 'auto';
      /** @default 1000 */
      tokenSoftCap: number;
      /** @default false */
      llmEnabled: boolean;
    };
    AuditLogEntry: {
      id: string;
      actorHandle: string;
      action: string;
      target: string;
      meta?: string | null;
      createdAt: string;
    };
    /** @description Opaque review payload produced by the ingest pipeline. */
    ReviewOutputPayload: {
      [key: string]: unknown;
    };
    /** @description Opaque staged payload produced by the ingest pipeline. */
    StagedPayload: {
      [key: string]: unknown;
    };
    /** @description Opaque submission payload produced by the ingest pipeline. */
    SubmissionPayload: {
      [key: string]: unknown;
    };
    OkResponse: {
      ok: boolean;
    };
    ErrorResponse: {
      error: {
        code: string;
        message: string;
        fields?: {
          [key: string]: string;
        } | null;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
